### ISSUE TITLE
updating embedded_hal::digital::v1 to v2

### ISSUE THREAD

**Issue by libesz** [JoshMcguigan/shift-register-driver#2]
Hey! Thanks for this driver!
 I started to use it with the recent HAL and noticed that the expected OutputPin (in [embedded_hal::digital](https://docs.rs/embedded-hal/0.2.6/embedded_hal/digital/index.html)::v1) trait is already deprecated. Stm32 implementations are not even producing this version, so it is hard to use this driver now. V2 has some small change in the OutputPin trait which is easy to fix.
 I actually fixed the shift register driver to meet v2. Would you mind a PR which does this update (without v1 support onwoards)?

**Comment by JoshMcguigan** [comment]
Hey, thanks for the feedback. I'd definitely be open to a PR with your proposed change .
